changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
  categories:
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
        - optimization
    - title: UI & Design
      labels:
        - ui
        - design
    - title: Other Changes
      labels:
        - '*'
