#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint sqflite_tvos.podspec` to validate before publishing.
#
# Generated by `flutter-tvos plugin port`. License holder: The FlutterTV Authors.
#
Pod::Spec.new do |s|
  s.name             = 'sqflite_tvos'
  s.version          = '0.0.1'
  s.summary          = 'tvOS implementation of sqflite.'
  s.description      = <<-DESC
tvOS implementation of sqflite, the federated platform
package that ships native code targeting Apple tvOS.
                       DESC
  s.homepage         = 'https://github.com/fluttertv/sqflite_tvos'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'The FlutterTV Authors' => 'noreply@fluttertv.dev' }
  s.source           = { :path => '.' }
  s.source_files     = 'Classes/**/*.{h,m,mm,swift}'
  s.public_header_files = 'Classes/**/include/**/*.h'
  s.platform         = :tvos, '13.0'
  s.swift_version    = '5.0'

  # Ships the privacy manifest so the sqflite_tvos.framework embedded in the
  # app carries Apple's required PrivacyInfo.xcprivacy (ITMS-91061 otherwise:
  # "Missing privacy manifest" for the sqflite SDK). The file already existed
  # under Resources/ but was never wired into the pod's build output.
  s.resource_bundles = {
    'sqflite_tvos_privacy' => ['Resources/PrivacyInfo.xcprivacy']
  }

  # IMPORTANT: this podspec must not depend on the Flutter CocoaPod. That
  # pod does not declare tvOS support, so adding a dependency on it breaks
  # `pod install` for tvOS consumers. Flutter.framework is resolved via
  # FRAMEWORK_SEARCH_PATHS, populated by the host app's Podfile.
  s.xcconfig         = {
    'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/../Flutter"',
    'OTHER_SWIFT_FLAGS'      => '$(inherited) -DTARGET_OS_TV',
  }
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end
