// swift-tools-version: 5.9
// Generated by `flutter-tvos plugin port`. Do not edit by hand.
//
// This manifest lets the package be consumed via Swift Package Manager. The
// target reuses the same `Classes/` sources the CocoaPods podspec compiles, so
// both dependency managers stay in sync from a single source tree.
import PackageDescription

let package = Package(
  name: "flutter_secure_storage_tvos",
  platforms: [
    .tvOS(.v13),
  ],
  products: [
    .library(name: "flutter-secure-storage-tvos", targets: ["flutter_secure_storage_tvos"]),
  ],
  dependencies: [
    // Lets the target `import Flutter`. flutter-tvos generates a FlutterFramework
    // package (binary target wrapping Flutter.xcframework) as a sibling of this
    // package under the app's ephemeral SwiftPM packages, so `../FlutterFramework`
    // resolves at build time. Matches stock Flutter's plugin Package.swift.
    .package(name: "FlutterFramework", path: "../FlutterFramework"),
  ],
  targets: [
    .target(
      name: "flutter_secure_storage_tvos",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework"),
      ],
      path: "Classes",
      swiftSettings: [
        // Keep Swift `#if TARGET_OS_TV` branches active, matching the podspec.
        .define("TARGET_OS_TV"),
      ]
    ),
  ]
)
